count: 10
coord_output: true
mask_output: true
glyph_coord_output: true
glyph_mask_output: true
corpus:
  paths: [resources/corpus/mjsynth.txt]
  # paths: [resources/corpus/test_corpus.txt]
  weights: [1]
  min_length: 1
  max_length: 25
  textcase: [lower, upper, capitalize]

font:
  paths: [resources/font]
  weights: [1]
  size: [32, 64]
  bold: 0.5

color:
  rgb: [[0, 255], [0, 255], [0, 255]]
  alpha: [1, 1]
  grayscale: 0

layout:
  length: [512, 512]
  space: [0, 0]
  line_space: [16, 16]
  # align: [left, center, right, justify]
  line_align: [middle]
  ltr: true
  ttb: true
  vertical: false

texture:
  prob: 0.5
  args:
    paths: [resources/image]
    weights: [1]
    alpha: [0, 1]
    grayscale: 0
    crop: 1

colormap3:
  paths: [resources/colormap/iiit5k_gray.txt]
  weights: [1]
  k: 3
  alpha: [1, 1]
  colorize: 1
color2:
  gray: [0, 255]
  alpha: [1, 1]
  colorize: 1

style:
  prob: 0.25
  args:
    weights: [1, 2, 2]
    args:
      # text border
      - size: [1, 12]
        alpha: [1, 1]
        grayscale: 0
      # text shadow
      - distance: [1, 6]
        angle: [0, 360]
        alpha: [0.3, 0.7]
        grayscale: 0
      # text extrusion
      - length: [1, 12]
        angle: [0, 360]
        alpha: [1, 1]
        grayscale: 0
pad:
  prob: 1
  args:
    pxs: [[0, 10], [0, 10], [0, 10], [0, 10]]

shape:
  prob: 1
  args:
    weights: [1, 1]
    args:
      # elastic distortion
      - alpha: [15, 30]
        sigma: [4, 12]
      # elastic distortion
      - alpha: [0, 2]
        sigma: [0, 0.6]

transform:
  prob: 1
  args:
    weights: [1, 1, 1, 1, 1, 1, 2]
    args:
      # perspective x
      - percents: [[0.5, 1], [1, 1]]
        aligns: [[0, 0], [0, 0]]
      # perspective y
      - percents: [[1, 1], [0.5, 1]]
        aligns: [[0, 0], [0, 0]]
      # trapezoidate x
      - weights: [1, 0, 1, 0]
        percent: [0.75, 1]
        align: [-1, 1]
      # trapezoidate y
      - weights: [0, 1, 0, 1]
        percent: [0.5, 1]
        align: [-1, 1]
      # skew x
      - weights: [1, 0]
        angle: [0, 30]
        ccw: 0.5
      # skew y
      - weights: [0, 1]
        angle: [0, 10]
        ccw: 0.5
      # rotate
      - angle: [0, 5]
        ccw: 0.5
postprocess:
  args:
    # gaussian noise
    - prob: 1
      args:
        scale: [4, 8]
        per_channel: 0
    # gaussian blur
    - prob: 0.9
      args:
        sigma: [0, 2]
    # resample
    - prob: 0.1
      args:
        size: [0.4, 0.4]
    # median blur
    - prob: 1
      args:
        k: [1, 1]
